import Link from "next/link";
import { ArrowUpRight, ChartNoAxesCombined, Mic2, ScanLine } from "lucide-react";
import { ThemeToggle } from "./components/ThemeToggle";

const stats = [{ value: "08", label: "vivas completed" }, { value: "84%", label: "average score" }, { value: "12h", label: "practice time" }];

export default function Home() {
  return <main className="page-grid min-h-screen"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-8">
    <header className="flex items-center justify-between"><Link href="/" className="font-[var(--font-display)] text-xl font-bold tracking-tight">Viva<span className="text-teal-600 dark:text-teal-300">Lens</span><span className="ml-1 text-xs font-normal text-slate-400">AI</span></Link><nav className="flex items-center gap-2"><Link href="/dashboard" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-slate-500 hover:text-[var(--ink)] sm:block">Progress</Link><ThemeToggle /></nav></header>
    <section className="grid items-end gap-10 pb-14 pt-20 lg:grid-cols-[1.2fr_.8fr] lg:pt-28"><div><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.24em] text-teal-600 dark:text-teal-300"><span className="h-2 w-2 rounded-full bg-teal-400" /> Your oral exam studio</p><h1 className="max-w-3xl font-[var(--font-display)] text-5xl font-bold leading-[.98] tracking-tight sm:text-7xl">Think clearly.<br /><span className="text-teal-600 dark:text-teal-300">Speak deeply.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">Turn your study material into a rigorous, conversational viva. Scan the source, answer aloud, and build the confidence to defend your thinking.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/viva" className="button-primary">Start a viva <ArrowUpRight className="h-4 w-4" /></Link><Link href="/dashboard" className="button-secondary">View your progress</Link></div></div><div className="panel relative overflow-hidden p-6 sm:p-8"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full border-[18px] border-teal-200/50 dark:border-teal-800/50" /><p className="relative text-sm font-semibold text-slate-500">This week</p><div className="relative mt-7 space-y-5">{stats.map((stat) => <div key={stat.label} className="flex items-end justify-between border-b border-[var(--line)] pb-4"><span className="font-[var(--font-display)] text-4xl font-bold">{stat.value}</span><span className="text-right text-sm text-[var(--muted)]">{stat.label}</span></div>)}</div><p className="relative mt-6 text-sm leading-6 text-[var(--muted)]">Your strongest improvement is in explaining concepts with evidence.</p></div></section>
    <section className="grid gap-3 border-t border-[var(--line)] py-8 sm:grid-cols-3">{[[ScanLine, "Scan context", "Bring the paper into focus."], [Mic2, "Answer aloud", "Practice the pressure of a real viva."], [ChartNoAxesCombined, "See patterns", "Know exactly where to go deeper."]].map(([Icon, title, text]) => <div key={title as string} className="flex gap-4 py-4"><Icon className="mt-1 h-5 w-5 shrink-0 text-teal-600 dark:text-teal-300" /><div><h2 className="font-semibold">{title as string}</h2><p className="mt-1 text-sm text-[var(--muted)]">{text as string}</p></div></div>)}</section>
  </div></main>;
}
